on:
    workflow_dispatch:
name: build
jobs:
    gradle-rc:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17
    
        - uses: gradle/actions/setup-gradle@v3
          id: setup-gradle
          with:
            gradle-version: 7.3.1
        # - run: gradle build --dry-run # just test build configuration
        - run: gradle bootJar --no-daemon
        - run: |
            ls -R build
        - run: |
            ./gradlew publishToLocalRepo
        - run: |
            ls -R build